receivers:
  otlp:
    protocols:
      grpc:
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  logging:
    logLevel: debug

  prometheus:
    endpoint: "0.0.0.0:4319"

service:
  telemetry:
    logs:
      level: "debug"

  pipelines:
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [logging, prometheus]

