version: 2
jobs:
  build:
    working_directory: /go/src/github.com/segmentio/stats
    docker:
      - image: circleci/golang
      - image: influxdb:1.8.9-alpine
        ports: ['8086:8086']
    steps:
      - checkout
      - setup_remote_docker: { reusable: true, docker_layer_caching: true }
      - run: go get -v -t ./...
      - run: go vet ./...
      - run: go test -v -race ./...
