---
name: golangci-lint
"on":
  push:
    tags:
      - v*
    paths:
      - '**.go'
      - .golangci.json
      - .github/workflows/golangci-lint.yml
  pull_request:
    branches:
      - main


jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest-large
    steps:
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e  # v7.0.0
        with:
          go-version: '>=1.26'

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Install golangci-lint
        # https://github.com/golangci/golangci-lint/tags
        run: |
          go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.12.2
          echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"

      - name: golangci-lint
        run: golangci-lint run
